language: rust

rust:
  - nightly
  - beta

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo test

after_success:
  - travis-cargo coveralls --no-sudo

    #env:
  #  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    #    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

dist: trusty
sudo: false

