[package]
name = "cookie-factory"
version = "0.2.1"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
license = "MIT"
repository = "https://github.com/Geal/cookie-factory"
readme = "README.md"
documentation = "http://docs.rs/cookie-factory"
description = "nom inspired serialization library"
categories = ["encoding"]
keywords = ["encoding", "serialization", "nom"]

[badges]
travis-ci = { repository = "Geal/cookie-factory" }
